### ISSUE TITLE
prepare_annotation_files should have an option to add custom circular DNA identifiers

### ISSUE THREAD

**Issue by spomlol** [ohlerlab/RiboseQC#1]
I used the prepare_annotation_files function on a custom GTF-file I have from S.cerevisiae, I got an error saying that a .test_seed was not found. After digging a bit into the code I found out that the seed-file is not created if it can't detect any circular sequences. Since I used de NC name for the mitochondrial sequence for S.cerevisiea (S288C) it didn't recognize it. I then added the name to the vector with the  DEFAULT_CIRC_SEQS and this fixed it.

Otherwise a really usefull and userfriendly tool that works great.

**Comment by ohlerlab** [comment]
Good idea! Glad you're finding the package useful.

I just fixed the issue, and added an ```additional_circ_seqs``` parameter to ```prepare_annotation_files```.
