### ISSUE TITLE
Is there any recommendation how the input .bam file should be prepared?

### ISSUE THREAD

**Issue by hollyjaro** [ohlerlab/RiboseQC#2]
Hello,

I am trying to use RiboseQC to create input files for SaTAnn package.
I was wondering, if there is a "right" way to prepare input .bam files for RiboseQC. I couldn't find anything about this in documentation nor in the preprint.
Currently my .bam files were prepared using STAR aligner on preprocessed data (adapter trimming and quality filtering using cutadapt, size filtering 25-35, rRNA & mtRNA filtering, deduplication using UMI_tools). The STAR was set to map to gencode_v29 genome/annotation (primary.assembly) and to keep only uniquely mapped reads. 

My main concern is whether to include multimappers or not and if so, to what extent (<20?). Does RiboseQC deals with multimapping reads?

Thank you!

Jaro

**Comment by zslastman** [comment]
Hey Jaro.
It sounds like you're processing the data pretty much the same way we did.

Multimappers should be included in the bam files. RiboseQC outputs separate data on uniquely mapping and multimapping reads, and if you're going to use the results with ORFquant, it will want that info - the default settings are to require periodicity in uniquely mapping reads, but info including multimapped reads is also included.

We also generally didn't include anything that mapped 20+ times.

**Comment by hollyjaro** [comment]
Thank you!
