### ISSUE TITLE
Error when preparing annotation files using data from the yeast vignette

### ISSUE THREAD

**Issue by jbbridgers** [ohlerlab/RiboseQC#4]
I get the following error: 

Error in .seqlengths_TwoBitFile(x) : UCSC library operation failed

**Comment by zslastman** [comment]
Hi! Thanks for reporting this. I've merge a number of changes into the master branch. The annotation processing has had some bug fixes, and the vignette now uses smaller, inbuilt data, rather than downloading the yeast annotation. Can you try the new version and see how it works for you?

**Comment by jbbridgers** [comment]
Thanks for getting back to me! I think I realized my issue. The Read Me document on the homepage directs people to download Ribo-seQC from Lorenzo Calviello's GitHub repo. It also has an older version of the vignette that I was trying to use. Might be helpful to update the read me with the appropriate vignette. Thanks so much!

**Comment by jbbridgers** [comment]
I ran into another issue with the RMD vignette document. On line 48 the following code didn't work for me on Windows 10: 

system(paste0('gunzip ',file.path(tmp_dir,basename(arab_fasta))))

My fix was to use this instead: 
R.utils::gunzip(file.path(tmp_dir,basename(arab_fasta)))

**Comment by zslastman** [comment]
Thanks, I"ll incorporate these changes. Let me know if the pipeline works on windows. We haven't tested it on windows systems, so it might hit issues with file paths.
