### ISSUE TITLE
RiboseQC_analysis does not work with multiple BAM files

### ISSUE THREAD

**Issue by Jelinek-J** [ohlerlab/RiboseQC#5]
There should probably be `resfilelist` instead of `resfile` on line [no. 2533 in `RiboseQC/R/riboseq_analysis.R`](https://github.com/ohlerlab/RiboseQC/blob/cbc33c48dfa681110ff454d517fbee5f05669aec/R/riboseq_analysis.R#L2533).
Currently it does not generate a html report when analyzing multiple files at once.

**Comment by opplatek** [comment]
I came to the same conclusion, tested it and works like a charm. Now it's in a pull request #6.
