### ISSUE TITLE
What software does RiboseQC depend on?

### ISSUE THREAD

**Issue by nh13** [ohlerlab/RiboseQC#8]
I tried following along the vignettes:
```
Creating html report in test_human_hek.html ... Thu Jun 18 15:41:42 2020
Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available)
```

This was solved by installing [pandoc](https://pandoc.org/installing.html). 

The README should describe the required tools and dependencies, both R packages as well as tools that should be on the path.

**Comment by zslastman** [comment]
Hi Nils.
In my understanding, pandoc is a dependency of rmarkdown, which is one of the existing R dependencies - it's odd that you had this issue. I'll add a note about it to the README.
